api_keys:
  openai: sk-X8yDYhrEWPNuklkKxsfdCr8Z3NyglMRPVjsTF5yxwTWvZ8nR
  google: sk-WkWVmcymzlLhjQtJVRjZChcvW2lid4Zfpwi9NDK8QnBJf5wz
  anthropic: sk-WkWVmcymzlLhjQtJVRjZChcvW2lid4Zfpwi9NDK8QnBJf5wz
  xai: sk-WkWVmcymzlLhjQtJVRjZChcvW2lid4Zfpwi9NDK8QnBJf5wz

data_path: "/home/zesen/AutoPI/data/open_prompt"

# Enhanced optimization settings
enhanced_optimization:
  # Number of variants to generate per mutation iteration
  n_variants_per_mutation: 5

  # Number of fixed user queries to test each variant with
  m_fixed_queries: 10

  # Threshold score for determining success
  threshold_score: 60.0

  # Enable early stopping when all queries achieve threshold
  early_stopping_enabled: true

# Variant generation settings
variant_generation:
  clear_agent_system_prompt: true
  instruction_prompt_file: "user_agnostic.txt"
